### ISSUE TITLE
Increment page that 'pagelinks' are appended to

### ISSUE THREAD

**Issue by patbegg** [box/viewer.js#155]
Hi Cam,
Following on from offsetting pages using a 'data provider', how would we modify the following code to also offset the page the 'pagelinks' (links extracted rom PDF) are appended to? At present the page offsetting is working but the page links are being appended to the wrong page because we can't offset them. This is the current data provider code:

```javascript
Crocodoc.addDataProvider('page-offset', function (scope) {
return {
get: function (type, key) {
var $p, dp = scope.getDataProvider(type);
if (type === 'metadata') {
$p = dp.get(type);
return $p.then(function (data) {
data.numpages += 1;
var page,
exceptions = data.dimensions.exceptions,
newExceptions = {};
for (page in exceptions) {
newExceptions[parseInt(page, 10) + 1] = exceptions[page];
}
data.dimensions.exceptions = newExceptions;
return data;
}).promise({
abort: $p.abort
});
} else if (type === 'page-svg' || type === 'page-text') {
key -= 1;
if (key === 0) {
return $.Deferred().resolve('').promise({
abort: function () {}
});
}
return dp.get(type, key);
} else if (type === 'page-img') {
key -= 1;
if (key === 0) {
return $.Deferred().resolve(new Image()).promise({
abort: function () {}
});
}
return dp.get(type, key);
}

    }
};
});

**Comment by lakenen** [comment]
@patbegg I'm going to close this issue, because you can look at (or use) the [page-manipulator plugin](https://github.com/box/viewer.js/tree/page-manipulator/plugins/page-manipulator) for this issue.
