### ISSUE TITLE
fullscreen plugin not loading from iframe

### ISSUE THREAD

**Issue by mifeng** [box/viewer.js#162]
For me the fullscreen plugin works normally, but not when the viewer is in an iframe, like in the examples on https://developers.box.com/view/

I'm using the plugin as described at:
https://github.com/box/viewer.js/tree/master/plugins/fullscreen

Using the options below to create iframe:
`<iframe src="[URL]" seamless allowfullscreen="allowfullscreen">`

**Comment by lakenen** [comment]
@mifeng does this happen for all browsers? Fullscreen in the iframe viewer at developeres.box.com/view works for me in Chrome.

**Comment by mifeng** [comment]
To clarify, fullscreen on the http://developers.box.com/view iframe viewer works perfectly.  However, when I tried the fullscreen plugin in our own iframe viewer, it didn't work (although it did without the iframe).  

I was wondering if there were anything needed to get it working inside an iframe

**Comment by lakenen** [comment]
The "allowfullscreen" property should be sufficient, if I recall correctly. Do you have a page I could look at to debug?

**Comment by mifeng** [comment]
thanks for the quick response - i'll post a link here in a couple of days that you can look at.

**Comment by mifeng** [comment]
not sure what i did to fix it, but it works for me using the "allowfullscreen" property.  initial testing seems to indicate that all browsers except for IE work.
