### ISSUE TITLE
Expose layout.scrollToOffset

### ISSUE THREAD

**Issue by blakevanlan** [box/viewer.js#180]
I'm writing a plugin for an application that needs to adjust the scroll position of the document. Currently, `layout.scrollBy` and `layout.scrollTo` are exposed through the viewer API and I'm wondering if it's worth my time to expose `layout. scrollToOffset` the same way or if there's a reason why it is not exposed.

Thanks!

**Comment by lakenen** [comment]
I'd rather not expose that method on the external API right now, but you can access it in a plugin context by looking at the `currentLayout` property on the viewer config. For example:

```js
Crocodoc.addPlugin('myplugin', function (scope) {
    var viewerConfig = scope.getConfig(),
        layout;

    return {
        messages: ['layoutchange'],
        onmessage: function (name) {
            if (name === 'layoutchange') {
                // it's sort of hacky :(
                layout = viewerConfig.currentLayout;
                layout.scrollToOffset(0, 500);
            }
        }
    };
});

var viewer = Crocodoc.createViewer(el, {
    url: '...',
    plugins: { myplugin: {} }
});
```

Does this solve your use case? You can expose stuff on the viewer instance by modifying the `viewerConfig.api` object.

**Comment by blakevanlan** [comment]
Yep that's basically what I was doing. It did feel hacky so I thought I'd see if you'd be interested in exposing these methods. Thanks!

**Comment by lakenen** [comment]
Ahh, gotcha. Yeah, I'd like to clean up some of that stuff. The way plugins work is sort of hacky in general, just because I didn't want to be too prescriptive on the sort of things plugins can do, so I figured just give access to all the internal objects and have fun. ¯\_(ツ)_/¯ 

1.0.0 will have a nicer interface :).

**Comment by blakevanlan** [comment]
Sounds good! Is there a rough estimate of when 1.0.0 will land?

**Comment by lakenen** [comment]
Unfortunately, no.
