### ISSUE TITLE
Ability to supply pre-signed URLs

### ISSUE THREAD

**Issue by cmcfadden** [box/viewer.js#183]
We'd like to load our viewer content directly off S3 (*not* cloudfront).  S3 doesn't seem to allow wildcard signing (CF does) so I don't believe there's a way to pass in a generic query parameter for all the assets within a path.

Ideally, we could pre-sign URLs for  all the assets in a folder, and pass them into viewer.js to use, instead of generating the URLs dynamically.  

Alternatively, I'd love to hear how other people are handling this.

**Comment by lakenen** [comment]
@cmcfadden there's not really an easy way to do it right now. If viewer.js were to expose some options for configuring individual asset URLs, do you have any idea what you'd like it to look like?

**Comment by cmcfadden** [comment]
As an example, I threw up a fork:
https://github.com/cmcfadden/viewer.js/tree/urlCallback

This adds an optional urlMutation function, passed during configuration.  Any URL will be passed through that before use.  In my implementation, I can put my AWS S3 signing code in that function, or use a precomputed array as appropriate. 

I don't know if this is the *right* approach, but it's one approach.

**Comment by lakenen** [comment]
@cmcfadden if you don't want to modify the main repo, you could also do this (it's kind of hacky, but it works):

```js

Crocodoc.addDataProvider('mutate-urls', function(scope) {
    'use strict';

    var config = scope.getConfig();

    return {
        get: function (objectType, key) {
            this._dp = scope.getDataProvider(objectType);
            // we need to clobber the getURL function, because it's called
            // from within dp.get()
            this._getURL = this._dp.getURL;
            this._dp.getURL = this.getURL.bind(this);

            // use the built-in data provider for whatever type this is
            return this._dp.get(objectType, key);
        },

        getURL: function (pageNum) {
            return config.urlMutation(this._getURL(pageNum));
        }
    };
});


var viewer = Crocodoc.createViewer(el, {
    url: '...',

    dataProviders: {
        metadata: 'mutate-urls',
        stylesheet: 'mutate-urls',
        'page-img': 'mutate-urls',
        'page-svg': 'mutate-urls',
        'page-text': 'mutate-urls'
    },

    urlMutation: function (url) {
        console.log(url);
        return url;
    }
});
```

There's no plan to add this as an option to viewer.js any time soon, but hopefully this will suffice for your purposes!

**Comment by cmcfadden** [comment]
Thanks so much for passing that on.  One note, in case folks stumble on this in the future. With the code above, I was getting an infinite recursion within getURL on multipage docs, because the second call to a given provider would set _getURL to the mutate-url's getURL method.   I did something like this to make sure we don't end up in that situation:

```
if(!this._dp.oldGetURL) {
this._dp.oldGetURL = this._dp.getURL;
}
this._getURL = this._dp.oldGetURL;
this._dp.getURL = this.getURL.bind(this);
```

**Comment by lakenen** [comment]
@cmcfadden good catch! I only tested with a one page doc. My bad :) I'll update my comment to avoid confusion!
