### ISSUE TITLE
Links in PPTX do not work

### ISSUE THREAD

**Issue by herosp** [box/viewer.js#184]
Links in PPTX files don't work. IE11/Chrome42

**Comment by lakenen** [comment]
@herosp this is a known issue, and links are not currently supported in PPT/PPTX formats. See: https://trello.com/c/QNm5gZxy/54-hyperlinks-are-not-preserved-after-conversion-of-ppt-pptx-files

**Comment by herosp** [comment]
Ok, thank you for your prompt reply.

Good job anyway

Regards

Henry Rosales
