### ISSUE TITLE
Viewer.js throws error when it is loaded inside an iframe which is inside a hidden div

### ISSUE THREAD

**Issue by reyuto** [box/viewer.js#185]
The embed widget used the viewer to display documents. However, the check code in resizer.js which calls util.getComputedStyle(element).position === 'static'(https://github.com/box/viewer.js/blob/master/src/js/components/resizer.js#L78) throws a JS Error because the element is inside an iframe and the iframe is hidden from the display. This root cause is a Firefox bug(https://bugzilla.mozilla.org/show_bug.cgi?id=548397), however, they are not planning to add a fix in the near term, and the least we can do is add a check, so that the js error can be prevented. Also, the viewer should work in the absence of getComputedStyle for an element returning a null.

**Comment by lakenen** [comment]
Ah, right, this is a regression from when I rewrote the resizer stuff. If you look at https://github.com/box/viewer.js/blob/master/src/js/components/resizer.js#L95, you'll see we had to deal with this somewhere else as well.

@reyuto, can you take a look? https://github.com/box/viewer.js/pull/186
