### ISSUE TITLE
Viewer refreshes when zoom-in or zoom-out is clicked. 

### ISSUE THREAD

**Issue by BenjaminHolland10** [box/viewer.js#189]
This happens on some documents where when zoom-in or zoom--out is clicked, the viewer will refresh and will start back on the first page. 
![screen shot 2015-06-09 at 11 10 41 am](https://cloud.githubusercontent.com/assets/10546097/8061262/0dadb264-0e98-11e5-851d-0ea8c72a1e2b.png)
![screen shot 2015-06-09 at 11 12 12 am](https://cloud.githubusercontent.com/assets/10546097/8061327/41b7d1a2-0e98-11e5-97e0-e2265fcaf683.png)

On viewer version v0.10.7

**Comment by lakenen** [comment]
@BenjaminHolland10 could you provide me with a document that will reproduce this error?
