### ISSUE TITLE
Question/Enhancement re: updating content as its rendered

### ISSUE THREAD

**Issue by mwaschkowski** [box/viewer.js#192]
Hi,

Getting started with the box view api and wondering if I can change the text/insert something by listening to events as the page is rendered? I've been looking for an example but can't find anything at that level.

As well, I'm guessing that the .svg files have everything they need to render the page within themselves, but is there any rendering mode that would allow the elements to be taken from the text-*.html files when rendering? I would love to be able to update the text-*.html file and have the rendering use the updated html...

Thanks

Mark

**Comment by lakenen** [comment]
The .html files are used for text selection only (they are rendered as transparent text). You could dig into the SVG content when the page loads, but it'd be very hacky and not work in all browsers, because in some cases the SVG is rendered with the `<iframe>` tag and others it's `<img>`.

**Comment by mwaschkowski** [comment]
OK, helps to know a bit more about how its rendering, thank you.
