### ISSUE TITLE
box/viewer.js free to use in an ERP

### ISSUE THREAD

**Issue by joomlaA1** [box/viewer.js#211]
@lakenen hello is box/viewer.js free to use in an ERP? thanks

and sry... where to post questions like this? thanks.

**Comment by chafreaky** [comment]
Viewer.js is an open source project, so the answer is yes, it is free to use, wherever you want...
As long as it complies with the [API Terms] (http://developers.box.com/box-view-terms/)  :+1:

**Comment by joomlaA1** [comment]
thanks
