### ISSUE TITLE
Text not rendering text correctly in Google Chrome 

### ISSUE THREAD

**Issue by coryschires** [box/viewer.js#213]
### Problem
Text is not rendering correctly in Google Chrome – on both Mac and Windows. As this GIF below demonstrates, the issue is present on [your demo site](https://view-upload.herokuapp.com). As you watch the GIF, I will highlight text which is missing or partially rendered.

![chrome_render_bug](https://cloud.githubusercontent.com/assets/104563/11791717/edbe4202-a267-11e5-82b0-3f8059d06313.gif)

### Additional information

* We've tested this issue on all modern browsers. As far as we can tell, it's only an issue on Google Chrome – both mac and win.
* We've seen the issue with many different files. But if it's helpful, we've primarily used this file while testing: 
[Nietzsche_critique_of_modernity.docx](https://github.com/box/viewer.js/files/61645/Nietzsche_critique_of_modernity.docx)
* It's probably not related to use of Chrome extensions. We've tested this on a freshly installed Google Chrome browser and the bug was still present. 
* I created a related post on the support forum three weeks ago: https://community.box.com/t5/Help-Forum/Bug-with-Box-View-API-on-Chrome/td-p/7732. No response whatsoever.

Please help! I'm hoping you guys can fix this on your end. But I'm also interested in an ideas for a workaround in the meantime.

**Comment by priyajeet** [comment]
This kind of feels like the Chrome's rendering layer is messing up on trying to render an SVG inside an iframe. If you have access to contents, try adding this CSS style 

```css
.crocodoc-page-svg object,
.crocodoc-page-svg iframe,
.crocodoc-page-svg img {
    transform: translateZ(0);
}
```

Or just try adding that style to this line https://github.com/box/viewer.js/blob/master/src/css/viewer.css#L127

**Comment by coryschires** [comment]
@priyajeet Thanks for the hint! We'll give it a try and let you know how it goes.

If this fix works, are you willing/interesting in merging a PR?

**Comment by priyajeet** [comment]
It's already merged. I believe you can try it on the demo page already.

**Comment by coryschires** [comment]
**Update:** This fix worked for us. Everything now looks good! Thanks!
