### ISSUE TITLE
Loading local assets with XHR

### ISSUE THREAD

**Issue by patbegg** [box/viewer.js#227]
Is there anyway to use the viewer outside of a webserver locally?
e.g. using
```
file:///Users/pat......./assets/info.json
```

I'm getting the usual error of 'Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.' when viewing in Chrome with a file:// url.

I can see the following in the source of viewer.js, but is this something different. Is there a way to use the viewer outside of a local webserver or am i barking up the wrong tree?

``` 
function isRequestToLocalFile(url) {
  return urlUtil.parse(url).protocol === 'file:';
}
```

**Comment by tonyjin** [comment]
You could try running Chrome with web security disabled and see if that works: http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

From the 'Common Issues' section of the README:
2. Are you loading assets from a file:// URL? Many browsers' security policies block these requests, so viewer.js is unable to load assets. To resolve this issue, you can run a local server using grunt serve (see Getting Started with the Code) or save your assets to some remote server for testing.
