### ISSUE TITLE
IOS 10 - Document text garbeled

### ISSUE THREAD

**Issue by adadgio** [box/viewer.js#231]
I have found the following issue on IOS 10 (iPhone 6) that appeared right after the IOS 10 update.

I have PDF documents transformed and displayed with `viewer.js` in an in app iOS webview but the text appears garbled when in vertical mode (it works well).

The issue does not happen on any other Android webview or mobile simulators. It does not happen when the phone is put in horizontal mode either.

It looks like a CSS letter spacing issue. I unfortunately lack means for debugging because i don't own the iOS app.

![img_7239](https://cloud.githubusercontent.com/assets/502070/19123715/055f64b6-8b30-11e6-9c8e-0c69ac1ecfb3.PNG)
![img_7240](https://cloud.githubusercontent.com/assets/502070/19123716/05689f68-8b30-11e6-932c-c8848f25adf5.PNG)

**Comment by richardchew** [comment]
We also encountered this problem in our app with iOS 10 too. It looks like something changed in iOS 10 with the rendering of fonts and when combined with the `viewer` library it sometimes uses a bigger `font-size` than it should be (in our case, the font was being rendered at `18px` when it should have been `12px`) and rendering a bigger font in the same amount of space makes it looks squished. After digging around a bit, we managed to find a way around it by getting the viewer to use a different embed strategy when rendering the `svg`. You can change it by passing it in the options when creating the viewer:

```
this.viewer = Crocodoc.createViewer(this.ui.fileViewer, {
  plugins: {
    ....
  },
  url: session.urls.assets,
  ...,
  embedStrategy: 3
});

```

For more details on `embedStrategy`, here's a snippet of the relevant code:

```
// Embed the svg directly in html via inline svg.
// @NOTE: NOT CURRENTLY USED -  seems to be slow everywhere, but I'm keeping
//        this here because it's very little extra code, and inline SVG might
//        be better some day?
EMBED_STRATEGY_INLINE_SVG = 3,
```

We tested this change in iOS in our in-app viewer (using `WKWebView`), Safari, Chrome and Firefox and it works well. We also tested it with some iOS 9 devices and it worked well there too. However, as the comments above mention, it does feel slower so it's not ideal but it worked for us.

**Comment by lancefisher** [comment]
Using `3` as the`embedStrategy` didn't work for me. However, `embedStrategy` of `8` seems to work okay.

**Comment by richardchew** [comment]
Oh interesting.... hmm, what kind of documents were you having trouble rendering? Ours was mostly docs, spreadsheets and presentations from both google docs and MS office.

**Comment by lancefisher** [comment]
I've been testing with docx.

**Comment by richardchew** [comment]
Thanks for letting us know. We also tested with docx and they seemed okay (both from an exported Google doc and one generated by MS office), so now i'm curious about what the differences are.

**Comment by adadgio** [comment]
I have tried both fixes but none of them worked. It got worse with the second option in fact.

Any other lead ?

**Comment by tonyjin** [comment]
I think I found a fix...

Adding -webkit-text-size-adjust: none; to the styles in each <head> block for the iframed svg layer fixes things.

Some related reading:
- https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust
- https://bugs.webkit.org/show_bug.cgi?id=84186 (? unsure if this is relevant)
- https://trac.webkit.org/changeset/206119 (? unsure if this is relevant, timeline & description seem relevant)

Will work on a patch & update to viewer.js

**Comment by adadgio** [comment]
Thank you for the fix. Which file can i download to try the fix ? The viewer js in the /src dir ?

**Comment by tonyjin** [comment]
Updated library is available at (either):
- https://github.com/box/viewer.js/tree/master/dist
- https://cdnjs.com/libraries/viewer.js

**Comment by adadgio** [comment]
Are you testing on Mobile safari or real iOS webviews ? I don't think it fixes the issue inside an iOs web view app. Not on my end.
